export default class Constants {
  constructor() {
    this.movieMoodTitles = [
      "The Sky Is Pink",
      "Bringing Up Baby",
      "Like crazy",
      "The Mist",
      "Pitch Perfect",
      "Lost In Translation",
      "Ginger Snaps",
      "Fight Club",
      "Buried",
      "My Life",
      "Illegal Tender",
      "The Commuter",
      "Sunshine Cleaning",
      "A Rainy Day In New York",
      "Fifty Shades Of Grey",
      "Her Side Of The Bed",
      "Moonlight",
      "The Hangover",
      "Nobody",
      "Paid In Full",
      "Coffee Shop",
      "Drinking Buddies",
      "Baby Blues",
      "The Feels",
      "Mamma Mia!",
      "A Smile Like Yours",
      "Black Rain",
      "The Diary Of A Teenage Girl",
      "Amélie",
      "Jurassic Park",
      "Booksmart",
      "Hitch",
      "The Dinner",
      "Begin Again",
      "The Proposal",
      "Paddington",
      "Wild",
      "Won't You Be My Neighbor?",
      "Fast And Furious",
      "Rocky",
      "The Other Guys",
      "Samaria",
      "The Champ",
      "Children Of Heaven",
      "The Photograph",
      "Sex And The City",
      "Sisters",
      "The Tallest Man On Earth",
    ];
    this.colorArray = [
      "#000000",
      "#56092D",
      "#2713BC",
      "#422FA8",
      "#9A63F5",
      "#5023B1",
      "#532CB3",
      "#610E05",
      "#A30D0D",
      "#BE4729",
      "#A10300",
      "#910106",
      "#D42605",
      "#C61F20",
      "#D9070D",
      "#C8220B",
      "#DD0502",
      "#C31B0B",
      "#DD7319",
      "#E89424",
      "#F37305",
      "#FA7C05",
      "#FEAA03",
      "#f7c1d0",
      "#fa0000",
      "#fc0a47",
      "#F25200",
      "#0B7611",
      "#055116",
      "#309956",
      "#007F25",
      "#0DA115",
      "#15C777",
      "#0CAD77",
      "#34AA8E",
      "#6DCEA0",
      "#096131",
      "#4DBAAD",
      "#51D893",
      "#4AB09D",
      "#145CAA",
      "#4BB1E4",
      "#139EEB",
      "#309ECC",
      "#2A6A8E",
      "#4183BF",
      "#467AF4",
      "#2096F7",
    ];
    this.spotifyKeywords = [
      "devastated",
      "coping",
      "heartache",
      "dark",
      "boost",
      "alone",
      "spooky",
      "crazy",
      "stress",
      "sad",
      "tender",
      "commute",
      "cleaning",
      "rainy day",
      "focus",
      "bed",
      "beats",
      "morning",
      "wake up",
      "work from home",
      "coffeehouse",
      "chill",
      "porch",
      "feels",
      "good vibes",
      "smile",
      "ballads",
      "caviar",
      "warm",
      "park",
      "feel-good",
      "date night",
      "dinner",
      "happy",
      "greatest",
      "perfect",
      "wild",
      "bad bitch",
      "cardio",
      "workout",
      "gameday",
      "tailgate",
      "champs",
      "beautiful",
      "love",
      "confidence",
      "party",
      "songs in the shower",
    ];
    this.inputKeywords = [
      "devastated",
      "mournful",
      "heartbroken",
      "dark",
      "beleaguered",
      "alone",
      "scared",
      "crazy",
      "stressed",
      "sad",
      "tender",
      "irritated",
      "fastidious",
      "bored",
      "preoccupied",
      "lazy",
      "studious",
      "sleepy",
      "eager",
      "busy",
      "caffeinated",
      "relaxed",
      "curious",
      "groovy",
      "dreamy",
      "playful",
      "emotional",
      "defiant",
      "cute",
      "cheerful",
      "upbeat",
      "sexy",
      "nostalgic",
      "happy",
      "timeless",
      "perfect",
      "adventurous",
      "sassy",
      "driven",
      "hardcore",
      "intense",
      "territorial",
      "triumphant",
      "beautiful",
      "amorous",
      "confident",
      "outgoing",
      "euphoric",
    ];
  }
}
