export default class Constants {
  
  constructor() {
    this.spotifyKeywords = [
      "devastated",
      "coping",
      "heartache",
      "dark",
      "boost",
      "alone",
      "spooky",
      "crazy",
      "stress",
      "sad",
      "tender",
      "commute",
      "cleaning",
      "rainy day",
      "focus",
      "bed",
      "beats",
      "morning",
      "wake up",
      "work from home",
      "coffeehouse",
      "chill",
      "porch",
      "feels",
      "good vibes",
      "smile",
      "ballads",
      "caviar",
      "warm",
      "park",
      "feel-good",
      "date night",
      "dinner",
      "happy",
      "greatest",
      "perfect",
      "wild",
      "bad bitch",
      "cardio",
      "workout",
      "gameday",
      "tailgate",
      "champs",
      "beautiful",
      "love",
      "confidence",
      "party",
      "songs in the shower",
    ];
    this.inputKeywords = [
      "devastated",
      "mournful",
      "heartbroken",
      "dark",
      "beleaguered",
      "alone",
      "scared",
      "crazy",
      "stressed",
      "sad",
      "tender",
      "irritated",
      "fastidious",
      "bored",
      "preoccupied",
      "lazy",
      "studious",
      "sleepy",
      "eager",
      "busy",
      "undercaffeinated",
      "relaxed",
      "curious",
      "groovy",
      "dreamy",
      "playful",
      "emotional",
      "defiant",
      "cute",
      "cheerful",
      "upbeat",
      "sexy",
      "nostalgic",
      "happy",
      "timeless",
      "perfect",
      "adventurous",
      "sassy",
      "driven",
      "hardcore",
      "intense",
      "territorial",
      "triumphant",
      "beautiful",
      "amorous",
      "confident",
      "outgoing",
      "euphoric",
    ];
  }
}